export const VENDOR_CATEGORIES: Record<string, string[]> = {
  Appliances: [
    "appliance",
    "appliances",
    "refrigerator",
    "dishwasher",
    "washer",
    "dryer",
    "oven",
    "stove",
    "microwave",
    "garbage disposal",
    "freezer",
    "ice machine",
    "water cooler",
    "kitchen equipment",
  ],

  "Architecture and Design": [
    "architect",
    "architecture",
    "architectural",
    "design services",
    "building design",
    "blueprint",
    "drafting",
    "space planning",
    "schematic design",
    "design-build",
  ],

  Asphalt: [
    "asphalt",
    "paving",
    "pavement",
    "blacktop",
    "resurfacing",
    "sealcoat",
    "seal coat",
    "striping",
    "parking lot",
    "hot mix",
    "asphalt repair",
    "pothole",
  ],

  Basement: [
    "basement",
    "foundation waterproofing",
    "crawl space",
    "crawlspace",
    "sump pump",
    "basement repair",
    "basement waterproofing",
    "basement finishing",
    "sub-grade",
  ],

  Bathroom: [
    "bathroom",
    "restroom",
    "lavatory",
    "toilet",
    "shower",
    "bathtub",
    "vanity",
    "bathroom renovation",
    "bathroom remodel",
    "commode",
    "urinal",
    "bath fixture",
  ],

  Cabinets: [
    "cabinet",
    "cabinetry",
    "countertop",
    "kitchen cabinet",
    "millwork",
    "casework",
    "cabinet installation",
    "cabinet refacing",
    "granite top",
    "quartz top",
    "laminate top",
  ],

  "Carpentry / Glaziery": [
    "carpentry",
    "carpenter",
    "glazier",
    "glazing",
    "woodwork",
    "framing",
    "trim",
    "molding",
    "glass installation",
    "door",
    "door installation",
    "wood framing",
    "finish carpentry",
    "rough carpentry",
    "storefront glass",
  ],

  Carpeting: [
    "carpet",
    "carpeting",
    "carpet installation",
    "carpet replacement",
    "floor covering",
    "rug",
    "carpet tile",
    "broadloom",
  ],

  Concrete: [
    "concrete",
    "cement",
    "masonry",
    "brick",
    "block",
    "cmu",
    "sidewalk",
    "curb",
    "concrete repair",
    "flatwork",
    "concrete pour",
    "stamped concrete",
    "concrete cutting",
    "concrete slab",
    "tilt-wall",
    "precast",
  ],

  "Decks and Porches": [
    "deck",
    "decking",
    "porch",
    "patio",
    "pergola",
    "gazebo",
    "outdoor structure",
    "railing",
    "balcony",
    "deck repair",
    "composite deck",
    "wood deck",
  ],

  Electrical: [
    "electrical",
    "electrician",
    "wiring",
    "lighting",
    "light fixture",
    "panel",
    "circuit",
    "outlet",
    "switch",
    "transformer",
    "elevator",
    "power distribution",
    "conduit",
    "switchgear",
    "breaker",
    "electrical service",
    "led lighting",
    "emergency lighting",
    "electrical repair",
    "electrical upgrade",
  ],

  "Equipment Rental": [
    "equipment rental",
    "tool rental",
    "heavy equipment rental",
    "crane rental",
    "scaffold rental",
    "lift rental",
    "machinery rental",
    "forklift rental",
    "backhoe rental",
    "bobcat rental",
  ],

  Excavating: [
    "excavat",
    "grading",
    "earthwork",
    "trenching",
    "demolition",
    "site preparation",
    "land clearing",
    "backfill",
    "site work",
    "mass grading",
    "rough grading",
    "dirt work",
    "excavation",
  ],

  "Exterior Cleaning": [
    "pressure wash",
    "power wash",
    "exterior cleaning",
    "building wash",
    "facade cleaning",
    "graffiti removal",
    "softwash",
    "soft wash",
    "exterior wash",
  ],

  "Exterior Installation": [
    "siding",
    "exterior install",
    "cladding",
    "stucco installation",
    "brick veneer",
    "exterior panel",
    "awning",
    "canopy",
    "exterior cladding",
    "rain screen",
    "exterior finish",
  ],

  "Exterior Maintenance": [
    "exterior maintenance",
    "building exterior",
    "facade repair",
    "caulking",
    "weatherproofing",
    "exterior repair",
    "tuckpointing",
    "joint sealant",
    "exterior restoration",
  ],

  Fencing: [
    "fence",
    "fencing",
    "gate",
    "chain link",
    "wrought iron fence",
    "security fence",
    "perimeter fence",
    "fence installation",
    "fence repair",
    "bollard",
    "guardrail",
  ],

  Flooring: [
    "flooring",
    "floor",
    "tile",
    "hardwood",
    "vinyl",
    "laminate",
    "epoxy floor",
    "floor refinish",
    "terrazzo",
    "lvt",
    "lvp",
    "vinyl plank",
    "ceramic tile",
    "porcelain tile",
    "floor tile",
    "resilient flooring",
    "polished concrete",
  ],

  Garage: [
    "garage",
    "garage door",
    "parking structure",
    "carport",
    "overhead door",
    "garage door opener",
    "parking garage",
    "garage repair",
  ],

  Gas: [
    "gas line",
    "natural gas",
    "gas piping",
    "gas installation",
    "gas service",
    "propane",
    "gas leak",
    "gas meter",
    "gas fitting",
    "gas valve",
  ],

  Generators: [
    "generator",
    "backup power",
    "standby power",
    "emergency power",
    "ups system",
    "power generation",
    "generator installation",
    "generator maintenance",
    "transfer switch",
    "diesel generator",
  ],

  Gutters: [
    "gutter",
    "downspout",
    "rain gutter",
    "gutter guard",
    "gutter installation",
    "gutter repair",
    "gutter cleaning",
    "seamless gutter",
    "leaf guard",
  ],

  HVAC: [
    "hvac",
    "heating",
    "ventilation",
    "air conditioning",
    "boiler",
    "furnace",
    "chiller",
    "air handler",
    "ductwork",
    "air duct",
    "thermostat",
    "refrigeration",
    "cooling",
    "heat pump",
    "mechanical system",
    "building automation",
    "ahu",
    "rtu",
    "rooftop unit",
    "split system",
    "mini split",
    "vav",
    "variable air volume",
    "cooling tower",
    "condensing unit",
    "air filter",
    "hvac filter",
    "hvac maintenance",
    "hvac repair",
  ],

  "Hazard Abatement": [
    "hazard abatement",
    "asbestos",
    "lead abatement",
    "mold remediation",
    "hazardous material",
    "environmental remediation",
    "abatement",
    "hazmat",
    "lead paint",
    "contamination",
    "pcb removal",
    "mold removal",
    "industrial hygiene",
    "acm",
    "lead inspection",
  ],

  "Hearth and Chimney": [
    "chimney",
    "fireplace",
    "hearth",
    "chimney sweep",
    "flue",
    "chimney repair",
    "chimney cleaning",
    "chimney liner",
    "fireplace insert",
    "wood stove",
  ],

  Insulation: [
    "insulation",
    "insulating",
    "spray foam",
    "fiberglass insulation",
    "thermal insulation",
    "weatherization",
    "batt insulation",
    "blown-in insulation",
    "rigid insulation",
    "pipe insulation",
  ],

  "Interior Cleaning": [
    "janitorial",
    "custodial",
    "interior cleaning",
    "office cleaning",
    "commercial cleaning",
    "floor cleaning",
    "building cleaning",
    "sanitation",
    "cleaning service",
    "housekeeping",
    "janitor",
    "day porter",
    "floor care",
    "restroom cleaning",
  ],

  "Interior Decoration": [
    "interior decoration",
    "interior design",
    "furnishing",
    "furniture",
    "window treatment",
    "blinds",
    "curtain",
    "upholstery",
    "drapery",
    "office furniture",
    "workstation",
    "cubicle",
  ],

  "Interior Installation": [
    "drywall",
    "ceiling",
    "partition",
    "acoustic panel",
    "drop ceiling",
    "interior construction",
    "suspended ceiling",
    "ceiling tile",
    "acoustic ceiling",
    "wall panel",
    "interior wall",
    "gypsum board",
    "sheetrock",
    "metal stud",
    "framing interior",
  ],

  "Interior Maintenance": [
    "interior maintenance",
    "building maintenance",
    "facility maintenance",
    "repair and maintenance",
    "handyman",
    "general maintenance",
    "preventive maintenance",
    "facility repair",
    "building repair",
    "maintenance service",
  ],

  "Lawn and Landscaping": [
    "landscaping",
    "lawn",
    "mowing",
    "irrigation",
    "sprinkler",
    "tree trimming",
    "tree removal",
    "groundskeeping",
    "turf",
    "horticulture",
    "garden",
    "grounds maintenance",
    "lawn care",
    "mulch",
    "sod",
    "landscape design",
    "hardscape",
    "landscape maintenance",
    "weed control",
    "bush trimming",
  ],

  "Life Safety": [
    "fire alarm",
    "fire protection",
    "sprinkler system",
    "fire suppression",
    "life safety",
    "fire extinguisher",
    "smoke detector",
    "fire escape",
    "emergency lighting",
    "fire safety",
    "fire sprinkler",
    "fire panel",
    "fire damper",
    "backflow preventer",
    "fire code",
  ],

  Metalwork: [
    "metalwork",
    "welding",
    "steel fabrication",
    "metal fabrication",
    "structural steel",
    "ornamental metal",
    "iron work",
    "sheet metal",
    "metal railing",
    "metal stair",
    "handrail",
    "misc metals",
  ],

  Moving: [
    "moving",
    "relocation",
    "furniture moving",
    "office relocation",
    "moving services",
    "furniture relocation",
    "movers",
  ],

  Paint: [
    "paint",
    "painting",
    "coating",
    "primer",
    "interior painting",
    "exterior painting",
    "industrial coating",
    "surface preparation",
    "wall painting",
    "line striping",
    "epoxy coating",
    "paint contractor",
    "repainting",
  ],

  Plaster: [
    "plaster",
    "plastering",
    "stucco repair",
    "drywall repair",
    "skim coat",
    "wall repair",
    "plaster repair",
    "veneer plaster",
    "plaster restoration",
  ],

  Plumbing: [
    "plumbing",
    "plumber",
    "pipe",
    "piping",
    "drain",
    "sewer",
    "water heater",
    "water line",
    "backflow",
    "fixture",
    "water supply",
    "sanitary",
    "domestic water",
    "waste line",
    "plumbing repair",
    "water pipe",
    "sewer line",
    "grease trap",
    "plumbing fixture",
  ],

  Roofing: [
    "roof",
    "roofing",
    "shingle",
    "membrane",
    "flat roof",
    "roof repair",
    "roof replacement",
    "flashing",
    "roof coating",
    "metal roof",
    "commercial roofing",
    "tpo",
    "epdm",
    "built-up roof",
    "standing seam",
    "roof leak",
    "roof inspection",
    "re-roof",
  ],

  Security: [
    "security",
    "access control",
    "surveillance",
    "camera",
    "security system",
    "alarm system",
    "cctv",
    "intrusion detection",
    "badge reader",
    "security guard",
    "card reader",
    "security camera",
    "video surveillance",
    "door access",
    "key card",
  ],

  "Structural Work": [
    "structural",
    "structural repair",
    "load bearing",
    "beam",
    "column",
    "structural steel",
    "structural engineer",
    "foundation repair",
    "retaining wall",
    "structural assessment",
    "structural modification",
    "shoring",
  ],

  "Surveys and Appraisal": [
    "survey",
    "surveying",
    "land survey",
    "appraisal",
    "property appraisal",
    "boundary survey",
    "topographic",
    "building inspection",
    "property assessment",
    "alta survey",
    "site survey",
    "condition assessment",
  ],

  "Wall-Making": [
    "wall construction",
    "partition wall",
    "retaining wall",
    "masonry wall",
    "block wall",
    "wall framing",
    "curtain wall",
    "demising wall",
    "cmu wall",
  ],

  Wallpaper: [
    "wallpaper",
    "wall covering",
    "wall vinyl",
    "wallpaper installation",
    "wallpaper removal",
    "wall fabric",
  ],

  "Waste Management": [
    "waste management",
    "dumpster",
    "trash",
    "debris removal",
    "waste disposal",
    "recycling",
    "demolition debris",
    "junk removal",
    "waste hauling",
    "roll-off",
    "trash removal",
    "solid waste",
    "waste collection",
  ],

  Windows: [
    "window",
    "window installation",
    "window replacement",
    "glass",
    "glazing",
    "window repair",
    "storefront",
    "skylight",
    "window film",
    "window tint",
    "window frame",
    "double pane",
    "insulated glass",
  ],

  "General Contractors": [
    "general contractor",
    "construction",
    "renovation",
    "remodel",
    "building construction",
    "tenant improvement",
    "build-out",
    "construction management",
    "construction manager",
    "cm at risk",
    "design-build",
    "job order contract",
    "joc",
    "cmar",
    "general construction",
    "building renovation",
    "turnkey",
    "construction project",
  ],
};
